version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_bot
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

volumes:
  redis_data: